name: washio
description: "A Simple washing machine booking app."
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter

  # Essential packages
  http: ^1.2.2
  intl: ^0.19.0
  supabase_flutter: ^2.6.0
  shared_preferences: ^2.0.17
  

  # Icons and images packages
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  image_path: "assets/icons/app-icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/main-icon.png
    - assets/icons/info-icon.svg

  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: fonts/JetBrainsMono-Regular.ttf
        - asset: fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: fonts/JetBrainsMono-Italic.ttf
          style: italic
